#!/bin/bash
# To be executed from project root (../ relatively to this file)

# CONFIG:

cxx_files=$(find . -iname "*.cxx")

hs_files=$(find . -iname "*.hs")


hs_include_dirs=""  # Colon-separated list. If empty, then not considerated

build_dir="_build"

cxx_libs="-lstdc++"  # Args preceded by -l
cxx_include_dirs=""  # Args preceded by -I
cxx_lib_dirs=""  # Args preceded by -L

#--------------------------------------

target()
{
    t="$1"
    shift
    mkdir -p "$build_dir/$t"
    inc=""
    [ -n "$hs_include_dirs" ] && inc=-i"$hs_include_dirs"
    eval ghc "$inc" -outputdir "$build_dir/$t" "$@" 
}

build_cxx_check()
{
    target "check" -v0 -O0 -fPIC -shared $cxx_files $cxx_libs $cxx_include_dirs $cxx_lib_dirs -o "$build_dir/check/libcxxforcheck.so"
}

build_check()
{
    build_cxx_check &&
    target "check" -v0 -O0 -no-link $hs_files
}

build_hs_tags()
{
    hasktags -cx .
}

build_tags()
{
    build_hs_tags &&
    ctags --extra=+q --recurse --append
}

normal_build()
{
    t="$1"
    shift
    target "$t" $hs_files $cxx_files $cxx_libs $cxx_include_dirs $cxx_lib_dirs -o "$build_dir/$t/main" "$@"
}

build_incremental()
{
    normal_build "incremental"
}

build_final()
{
    normal_build "final" -O2
}

#--------------------------------------

if [ -n "$1" ]; then
    eval "build_$1"
else
    build_incremental
fi

